import {
  Bed,
  Patient,
  Document,
  Claim,
  Activity,
  DailyExpense,
  ApprovalHistory,
} from "./types";

export const beds: Bed[] = [
  // General Ward
  { id: "b1", bedNumber: "G-101", ward: "General", status: "occupied", patientId: "p1" },
  { id: "b2", bedNumber: "G-102", ward: "General", status: "available" },
  { id: "b3", bedNumber: "G-103", ward: "General", status: "occupied", patientId: "p2" },
  { id: "b4", bedNumber: "G-104", ward: "General", status: "available" },
  { id: "b5", bedNumber: "G-105", ward: "General", status: "maintenance" },
  { id: "b6", bedNumber: "G-106", ward: "General", status: "available" },
  
  // ICU
  { id: "b7", bedNumber: "ICU-201", ward: "ICU", status: "occupied", patientId: "p3" },
  { id: "b8", bedNumber: "ICU-202", ward: "ICU", status: "available" },
  { id: "b9", bedNumber: "ICU-203", ward: "ICU", status: "occupied", patientId: "p4" },
  { id: "b10", bedNumber: "ICU-204", ward: "ICU", status: "available" },
  
  // Pediatric
  { id: "b11", bedNumber: "P-301", ward: "Pediatric", status: "occupied", patientId: "p5" },
  { id: "b12", bedNumber: "P-302", ward: "Pediatric", status: "available" },
  { id: "b13", bedNumber: "P-303", ward: "Pediatric", status: "available" },
  { id: "b14", bedNumber: "P-304", ward: "Pediatric", status: "maintenance" },
  
  // Maternity
  { id: "b15", bedNumber: "M-401", ward: "Maternity", status: "occupied", patientId: "p6" },
  { id: "b16", bedNumber: "M-402", ward: "Maternity", status: "available" },
  { id: "b17", bedNumber: "M-403", ward: "Maternity", status: "available" },
  { id: "b18", bedNumber: "M-404", ward: "Maternity", status: "occupied", patientId: "p7" },
  
  // Emergency
  { id: "b19", bedNumber: "E-501", ward: "Emergency", status: "available" },
  { id: "b20", bedNumber: "E-502", ward: "Emergency", status: "available" },
  { id: "b21", bedNumber: "E-503", ward: "Emergency", status: "occupied", patientId: "p8" },
  { id: "b22", bedNumber: "E-504", ward: "Emergency", status: "available" },
];

export const patients: Patient[] = [
  {
    id: "p1",
    name: "John Smith",
    age: 45,
    gender: "Male",
    admissionDate: "2026-01-05",
    diagnosis: "Pneumonia",
    assignedBed: "G-101",
    status: "Admitted",
    phone: "+1-555-0101",
    email: "john.smith@email.com",
    address: "123 Main St, City, State 12345",
    emergencyContact: "+1-555-0102",
    bloodGroup: "O+",
    allergies: "Penicillin",
    medications: "Amoxicillin, Ibuprofen",
  },
  {
    id: "p2",
    name: "Sarah Johnson",
    age: 32,
    gender: "Female",
    admissionDate: "2026-01-07",
    diagnosis: "Appendicitis",
    assignedBed: "G-103",
    status: "Admitted",
    phone: "+1-555-0201",
    email: "sarah.j@email.com",
    address: "456 Oak Ave, City, State 12345",
    emergencyContact: "+1-555-0202",
    bloodGroup: "A+",
    allergies: "None",
    medications: "Pain relievers",
  },
  {
    id: "p3",
    name: "Michael Brown",
    age: 67,
    gender: "Male",
    admissionDate: "2026-01-03",
    diagnosis: "Cardiac Arrest",
    assignedBed: "ICU-201",
    status: "Admitted",
    phone: "+1-555-0301",
    email: "m.brown@email.com",
    address: "789 Pine Rd, City, State 12345",
    emergencyContact: "+1-555-0302",
    bloodGroup: "B+",
    allergies: "Sulfa drugs",
    medications: "Beta blockers, Aspirin",
  },
  {
    id: "p4",
    name: "Emily Davis",
    age: 28,
    gender: "Female",
    admissionDate: "2026-01-08",
    diagnosis: "Severe Asthma Attack",
    assignedBed: "ICU-203",
    status: "Admitted",
    phone: "+1-555-0401",
    email: "emily.d@email.com",
    address: "321 Elm St, City, State 12345",
    emergencyContact: "+1-555-0402",
    bloodGroup: "AB+",
    allergies: "Pollen, Dust",
    medications: "Albuterol, Corticosteroids",
  },
  {
    id: "p5",
    name: "Tommy Wilson",
    age: 8,
    gender: "Male",
    admissionDate: "2026-01-09",
    diagnosis: "Broken Arm",
    assignedBed: "P-301",
    status: "Admitted",
    phone: "+1-555-0501",
    email: "wilson.family@email.com",
    address: "654 Maple Dr, City, State 12345",
    emergencyContact: "+1-555-0502",
    bloodGroup: "O-",
    allergies: "Latex",
    medications: "Pain management",
  },
  {
    id: "p6",
    name: "Jessica Martinez",
    age: 29,
    gender: "Female",
    admissionDate: "2026-01-06",
    diagnosis: "Pregnancy - Term",
    assignedBed: "M-401",
    status: "Admitted",
    phone: "+1-555-0601",
    email: "j.martinez@email.com",
    address: "987 Cedar Ln, City, State 12345",
    emergencyContact: "+1-555-0602",
    bloodGroup: "A-",
    allergies: "None",
    medications: "Prenatal vitamins",
  },
  {
    id: "p7",
    name: "Amanda Taylor",
    age: 31,
    gender: "Female",
    admissionDate: "2026-01-04",
    diagnosis: "C-Section Recovery",
    assignedBed: "M-404",
    status: "Admitted",
    phone: "+1-555-0701",
    email: "a.taylor@email.com",
    address: "147 Birch St, City, State 12345",
    emergencyContact: "+1-555-0702",
    bloodGroup: "B-",
    allergies: "None",
    medications: "Antibiotics, Pain relief",
  },
  {
    id: "p8",
    name: "Robert Anderson",
    age: 52,
    gender: "Male",
    admissionDate: "2026-01-10",
    diagnosis: "Motor Vehicle Accident",
    assignedBed: "E-503",
    status: "Admitted",
    phone: "+1-555-0801",
    email: "r.anderson@email.com",
    address: "258 Willow Way, City, State 12345",
    emergencyContact: "+1-555-0802",
    bloodGroup: "AB-",
    allergies: "Morphine",
    medications: "Pain management, Antibiotics",
  },
  {
    id: "p9",
    name: "Linda White",
    age: 58,
    gender: "Female",
    admissionDate: "2025-12-28",
    dischargeDate: "2026-01-09",
    diagnosis: "Hip Replacement",
    status: "Discharged",
    phone: "+1-555-0901",
    email: "l.white@email.com",
    address: "369 Spruce Ave, City, State 12345",
    emergencyContact: "+1-555-0902",
    bloodGroup: "O+",
    allergies: "None",
    medications: "Physical therapy, Pain management",
  },
  {
    id: "p10",
    name: "David Harris",
    age: 41,
    gender: "Male",
    admissionDate: "2025-12-30",
    dischargeDate: "2026-01-08",
    diagnosis: "Gallbladder Surgery",
    status: "Discharged",
    phone: "+1-555-1001",
    email: "d.harris@email.com",
    address: "741 Ash Ct, City, State 12345",
    emergencyContact: "+1-555-1002",
    bloodGroup: "A+",
    allergies: "Codeine",
    medications: "Antibiotics",
  },
];

export const documents: Document[] = [
  { id: "d1", patientId: "p1", type: "Report", name: "Chest X-Ray Report", date: "2026-01-05", url: "#" },
  { id: "d2", patientId: "p1", type: "Lab Result", name: "Blood Test Results", date: "2026-01-06", url: "#" },
  { id: "d3", patientId: "p1", type: "Prescription", name: "Medication Prescription", date: "2026-01-05", url: "#" },
  { id: "d4", patientId: "p2", type: "Report", name: "Ultrasound Report", date: "2026-01-07", url: "#" },
  { id: "d5", patientId: "p2", type: "Lab Result", name: "Pre-Surgery Tests", date: "2026-01-07", url: "#" },
  { id: "d6", patientId: "p3", type: "Report", name: "ECG Report", date: "2026-01-03", url: "#" },
  { id: "d7", patientId: "p3", type: "Lab Result", name: "Cardiac Enzyme Test", date: "2026-01-03", url: "#" },
  { id: "d8", patientId: "p9", type: "Discharge Summary", name: "Discharge Summary", date: "2026-01-09", url: "#" },
  { id: "d9", patientId: "p10", type: "Discharge Summary", name: "Discharge Summary", date: "2026-01-08", url: "#" },
];

const dailyExpensesForClaim1: DailyExpense[] = [
  {
    id: "de1",
    date: "2026-01-05",
    description: "Room charges - General Ward",
    amount: 500,
    status: "Approved",
    approvedAmount: 500,
  },
  {
    id: "de2",
    date: "2026-01-05",
    description: "X-Ray examination",
    amount: 300,
    status: "Approved",
    approvedAmount: 300,
  },
  {
    id: "de3",
    date: "2026-01-05",
    description: "Blood tests",
    amount: 200,
    status: "Approved",
    approvedAmount: 200,
  },
  {
    id: "de4",
    date: "2026-01-06",
    description: "Room charges - General Ward",
    amount: 500,
    status: "Approved",
    approvedAmount: 500,
  },
  {
    id: "de5",
    date: "2026-01-06",
    description: "Medications",
    amount: 150,
    status: "Approved",
    approvedAmount: 150,
  },
  {
    id: "de6",
    date: "2026-01-07",
    description: "Room charges - General Ward",
    amount: 500,
    status: "Pending",
  },
  {
    id: "de7",
    date: "2026-01-07",
    description: "Doctor consultation",
    amount: 200,
    status: "Pending",
  },
];

const approvalHistoryForClaim1: ApprovalHistory[] = [
  {
    id: "ah1",
    date: "2026-01-06",
    description: "Initial admission expenses approved",
    amount: 1000,
    status: "Approved",
  },
  {
    id: "ah2",
    date: "2026-01-07",
    description: "Day 2 treatment charges approved",
    amount: 650,
    status: "Approved",
  },
];

const dailyExpensesForClaim2: DailyExpense[] = [
  {
    id: "de8",
    date: "2026-01-03",
    description: "ICU admission",
    amount: 2000,
    status: "Approved",
    approvedAmount: 2000,
  },
  {
    id: "de9",
    date: "2026-01-03",
    description: "Emergency procedures",
    amount: 5000,
    status: "Approved",
    approvedAmount: 4500,
    notes: "Standard procedure charges applied",
  },
  {
    id: "de10",
    date: "2026-01-04",
    description: "ICU charges",
    amount: 2000,
    status: "Approved",
    approvedAmount: 2000,
  },
  {
    id: "de11",
    date: "2026-01-04",
    description: "Cardiac monitoring",
    amount: 800,
    status: "Rejected",
    notes: "Not covered under policy",
  },
  {
    id: "de12",
    date: "2026-01-05",
    description: "ICU charges",
    amount: 2000,
    status: "Approved",
    approvedAmount: 2000,
  },
];

const approvalHistoryForClaim2: ApprovalHistory[] = [
  {
    id: "ah3",
    date: "2026-01-04",
    description: "Emergency admission approved",
    amount: 7000,
    status: "Approved",
  },
  {
    id: "ah4",
    date: "2026-01-04",
    description: "Cardiac monitoring rejected",
    amount: 800,
    status: "Rejected",
  },
  {
    id: "ah5",
    date: "2026-01-06",
    description: "Continued ICU care approved",
    amount: 2000,
    status: "Approved",
  },
];

export const claims: Claim[] = [
  {
    id: "c1",
    patientId: "p1",
    patientName: "John Smith",
    policyNumber: "POL-2024-001",
    insurer: "HealthFirst Insurance",
    claimAmount: 2850,
    approvedAmount: 1650,
    pendingAmount: 700,
    rejectedAmount: 0,
    status: "Partial",
    submissionDate: "2026-01-06",
    diagnosis: "Pneumonia",
    treatment: "Antibiotics, Chest X-Ray, Hospitalization",
    expenses: dailyExpensesForClaim1,
    approvalHistory: approvalHistoryForClaim1,
  },
  {
    id: "c2",
    patientId: "p3",
    patientName: "Michael Brown",
    policyNumber: "POL-2023-542",
    insurer: "MediCare Plus",
    claimAmount: 11800,
    approvedAmount: 10500,
    pendingAmount: 0,
    rejectedAmount: 800,
    status: "Partial",
    submissionDate: "2026-01-04",
    diagnosis: "Cardiac Arrest",
    treatment: "Emergency cardiac care, ICU monitoring",
    expenses: dailyExpensesForClaim2,
    approvalHistory: approvalHistoryForClaim2,
  },
  {
    id: "c3",
    patientId: "p2",
    patientName: "Sarah Johnson",
    policyNumber: "POL-2024-789",
    insurer: "BlueCross Shield",
    claimAmount: 4500,
    approvedAmount: 0,
    pendingAmount: 4500,
    rejectedAmount: 0,
    status: "Pending",
    submissionDate: "2026-01-08",
    diagnosis: "Appendicitis",
    treatment: "Appendectomy surgery",
    expenses: [],
    approvalHistory: [],
  },
  {
    id: "c4",
    patientId: "p9",
    patientName: "Linda White",
    policyNumber: "POL-2023-334",
    insurer: "HealthFirst Insurance",
    claimAmount: 15000,
    approvedAmount: 15000,
    pendingAmount: 0,
    rejectedAmount: 0,
    status: "Approved",
    submissionDate: "2025-12-29",
    diagnosis: "Hip Replacement",
    treatment: "Total hip replacement surgery, post-op care",
    expenses: [],
    approvalHistory: [],
  },
];

export const activities: Activity[] = [
  {
    id: "a1",
    type: "admission",
    description: "Robert Anderson admitted to Emergency",
    time: "2 hours ago",
  },
  {
    id: "a2",
    type: "discharge",
    description: "Linda White discharged from General Ward",
    time: "1 day ago",
  },
  {
    id: "a3",
    type: "claim",
    description: "Claim approved for Michael Brown - $10,500",
    time: "2 days ago",
  },
  {
    id: "a4",
    type: "admission",
    description: "Tommy Wilson admitted to Pediatric",
    time: "1 day ago",
  },
  {
    id: "a5",
    type: "discharge",
    description: "David Harris discharged from General Ward",
    time: "2 days ago",
  },
  {
    id: "a6",
    type: "claim",
    description: "New claim submitted for Sarah Johnson",
    time: "2 days ago",
  },
];
